### ISSUE TITLE
non alpha characters in node-ids

### ISSUE THREAD

**Issue by TorstenBMR** [pontusbostrom/VaadinGraphvizComponent#1]
I geht "syntax error in line ..." when putting non-alpha-characters like "-" (minus) oder äöü (german Umlaute) in the label text or the id of a node.

**Comment by TorstenBMR** [comment]
nb: the error shows in the browser on the place where the component should be rendered.

**Comment by pontusbostrom** [comment]
The reason for the problem you mention is that viz.js, which does the actual graph generation, thinks that the input is invalid.  However, those characters seems to work for me. 

One thing that is important when using special characters is to ensure that they are enclosed with "", i.e. in Java use `node1.setParam("label", "\"Label!\"");`. By default viz.js should handle utf-8 encoded strings. If this has been changed somewhere that can cause problems. See [http://www.graphviz.org/doc/info/lang.html] for more info on accepted character encodings.

**Comment by TorstenBMR** [comment]
Thanks Pontus, this works like a charm! I'll close the issue.
Anyway it would be great if you could just hide this behaviour from viz.js and offer the possibility to pass plain strings in your methods. Thanks!

**Comment by pontusbostrom** [comment]
Great that it worked. Yes, you're right that it would be better if this was handled automatically. This is something that should be addressed in the next version.
