### ISSUE TITLE
allow subclassing

### ISSUE THREAD

**Issue by TorstenBMR** [pontusbostrom/VaadinGraphvizComponent#4]
Dear Pontus,

I need to subclass Edge so that I can create my own derived Edge-class.
E.g. I want to have some own methods that I can call, like:

myedge.setFancyLabelText(string) or whatever.

So it should be possible to have some 
   class MyEdge extends Edge 
    (...)

that I can create. Unfortunatly I cannot handover this own Edge to the graph as there is no method to put an Edge in (only chance is SubGraph.addEdge(source, dest) which creates an Edge itself.

**Comment by pontusbostrom** [comment]
Sorry for the delayed reply. Yes, this is a deficiency in the api. The focus has been more on controlling  the nodes than the edges. This is an issue I will try and fix as soon as possible, but I cannot promise it will happen in the coming week.

**Comment by pontusbostrom** [comment]
There is now the possibility to provide a custom factory for creating edges in master. Hope this provide the features you need.

**Comment by javydreamercsw** [comment]
Looks like this issue could be closed then...

**Comment by pontusbostrom** [comment]
Should be fixed in 1.0 and 2.0
