### ISSUE TITLE
CSS styles

### ISSUE THREAD

**Issue by ruvenij** [pontusbostrom/VaadinGraphvizComponent#5]
Hi,

For UMLDemoView.java you are using html tables. Is there a way to add css styles for that table components?

**Comment by pontusbostrom** [comment]
Hi,

Unfortunately no. As you can se in the e.g. the Chrome developer tools, the html-like tables have been converted to SVG before they are shown in the web browser. This output can be styled with CSS, but that will probably not be very useful. Nodes and edges themselves can be styled with css to some degree.

See http://www.graphviz.org/doc/info/shapes.html for more information on the subset of html that can be used in node labels.

**Comment by javydreamercsw** [comment]
Please close issue then.
