### ISSUE TITLE
Clearing css style

### ISSUE THREAD

**Issue by javydreamercsw** [pontusbostrom/VaadinGraphvizComponent#8]
I noticed the CSS style changes used to highlight the node/edge on click and that works fine, but how can we revert it? I guess setting stroke and fill back to black but then I'll need to get a list of nodes/edges.

There's no way to get a list of nodes and/or edges in the graph to iterate. I guess I could keep a copy of those in a list but seems like a waste of resources.

Basically what I want to do is to clear (revert to black) when user clicks another node/edge.

**Comment by pontusbostrom** [comment]
Sorry about the long delay. Just for reference, it is possible to unset a CSS property by setting it to null. I have updated the demo to show this.
